default_language_version:
    python: python3.12
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: mixed-line-ending
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-install
-   repo: local
    hooks:
    -   id: mypy-check
        name: mypy-check
        entry: poetry run mypy
        language: system
        pass_filenames: false
        types_or:
          - python
          - toml
    -   id: pytest-check
        name: pytest-check
        entry: poetry run pytest --cov-fail-under=100
        language: system
        pass_filenames: false
        types_or:
        -   html
        -   python
        -   toml
